kind: Deployment
apiVersion: apps/v1
metadata:
    name: abctechnologies-deployment
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: abc-technologies-app
    template:
        metadata:
            labels:
                app: abc-technologies-app
        spec:
            containers:
                - image: purushottam87/abctechnologies 
                  name:  abc-technologies-con-app
